{"uuid": "046b2791-bc5b-4a10-945a-23858e88b6b1", "children": ["2e576c98-def2-478b-ad2f-6f4445e9f732", "096ffcdc-4341-49e2-9c45-67630ca6f96d"], "befores": [{"name": "record", "status": "passed", "start": 1641897303522, "stop": 1641897303527}], "afters": [{"name": "record::0", "status": "broken", "statusDetails": {"message": "TypeError: file() got an unexpected keyword argument 'file_path'\n", "trace": "  File \"C:\\Users\\navy\\AppData\\Roaming\\Python\\Python38\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"d:\\program files\\lib\\site-packages\\_pytest\\fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"F:\\自动化测试\\15-UI自动化测试框架 - 步骤驱动、日志、截图、录屏\\testcase\\conftest.py\", line 20, in record\n    allure.attach.file(file_path=\"tmp.mp4\",  attachment_type=allure.attachment_type.MP4)\n"}, "start": 1641897340870, "stop": 1641897340871}], "start": 1641897303522, "stop": 1641897340871}